nohup python kfold_train_test.py --model_name klue/roberta-large \
                --use_wandb True \
                --user_name SujeongIm \
                --exp_name end_point_experiment \
                --eval_steps 300 \
                --save_steps 300 \
                --load_best_model_at_end True \
                --epochs 7 \
                --train_bs 64 \
                --eval_bs 64 \
                --loss_fn labelsmoothingloss \
                --smoothing 0.2 \
                --head_type modifiedBiLSTM \
                --train_data_dir /opt/ml/dataset/train/preprocess.csv \
                --data_preprocessing True \
                --add_entity_marker True \
                --entity_marker_type entity_marker_punc
